# Generated by Django 3.2 on 2022-03-22 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creattion date"
                    ),
                ),
                (
                    "upvotes",
                    models.PositiveIntegerField(verbose_name="amount of upvotes"),
                ),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="own",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=30, verbose_name="author name"),
                ),
                ("content", models.CharField(max_length=255, verbose_name="content")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creattion date"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="main.article",
                        verbose_name="article",
                    ),
                ),
            ],
        ),
    ]
